In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import itertools
import statsmodels.api as sm
from math import sqrt 
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf,plot_pacf
from pandas.tseries.offsets import DateOffset

In [16]:
wdata = pd.read_csv("cleaned_wdata.csv")

In [17]:
wdata.head(10)

,Date,Year,Month,Day,Hour,Minute,Temperature(F),Dew Point(F),Humidity(F),Wind,Wind Speed(mph),Wind Gust(mph),Pressure(in),Condition,Season
0,2010-01-01,2010,1,1,0,0,18,10,73,NW,16,0,29.71,Cloudy,Winter
1,2010-01-01,2010,1,1,1,0,36,34,93,SW,8,0,29.65,Fair,Winter
2,2010-01-01,2010,1,1,1,10,36,34,93,WSW,9,0,29.64,Fair,Winter
3,2010-01-01,2010,1,1,1,23,36,34,93,WSW,9,0,29.64,Mostly Cloudy,Winter
4,2010-01-01,2010,1,1,1,28,36,34,93,WSW,10,0,29.64,Mostly Cloudy,Winter
5,2010-01-01,2010,1,1,2,0,36,34,93,WSW,8,0,29.64,Partly Cloudy,Winter
6,2010-01-01,2010,1,1,2,6,36,34,93,WSW,10,0,29.63,Partly Cloudy,Winter
7,2010-01-01,2010,1,1,3,0,36,34,93,WSW,10,0,29.64,Fair,Winter
8,2010-01-01,2010,1,1,3,34,36,34,93,WSW,8,0,29.64,Fair,Winter
9,2010-01-01,2010,1,1,4,0,36,34,93,WSW,9,0,29.65,Mostly Cloudy,Winter

In [18]:
wdata.shape

(140463, 15)

In [21]:
# One-hot encoding for categorical variables
categorical_columns = ["Wind", "Condition", "Season"]
data_encoded = pd.get_dummies(wdata, columns=categorical_columns, drop_first=True)

In [23]:
data_encoded.head(10)

,Date,Year,Month,Day,Hour,Minute,Temperature(F),Dew Point(F),Humidity(F),Wind Speed(mph),...,Condition_T-Storm / Windy,Condition_Thunder,Condition_Thunder / Windy,Condition_Thunder in the Vicinity,Condition_Unknown Precipitation,Condition_Wintry Mix,Condition_Wintry Mix / Windy,Season_Spring,Season_Summer,Season_Winter
0,2010-01-01,2010,1,1,0,0,18,10,73,16,...,0,0,0,0,0,0,0,0,0,1
1,2010-01-01,2010,1,1,1,0,36,34,93,8,...,0,0,0,0,0,0,0,0,0,1
2,2010-01-01,2010,1,1,1,10,36,34,93,9,...,0,0,0,0,0,0,0,0,0,1
3,2010-01-01,2010,1,1,1,23,36,34,93,9,...,0,0,0,0,0,0,0,0,0,1
4,2010-01-01,2010,1,1,1,28,36,34,93,10,...,0,0,0,0,0,0,0,0,0,1
5,2010-01-01,2010,1,1,2,0,36,34,93,8,...,0,0,0,0,0,0,0,0,0,1
6,2010-01-01,2010,1,1,2,6,36,34,93,10,...,0,0,0,0,0,0,0,0,0,1
7,2010-01-01,2010,1,1,3,0,36,34,93,10,...,0,0,0,0,0,0,0,0,0,1
8,2010-01-01,2010,1,1,3,34,36,34,93,8,...,0,0,0,0,0,0,0,0,0,1
9,2010-01-01,2010,1,1,4,0,36,34,93,9,...,0,0,0,0,0,0,0,0,0,1

In [26]:
# Defining features (X) and target variable (y)
X = data_encoded.drop(["Temperature(F)", "Date"], axis=1)
y = data_encoded["Temperature(F)"]

In [27]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
# Model training using RandomForestRegressor
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [29]:
# Predictions
y_pred = model.predict(X_test)

In [30]:
# Evaluation
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.17454783397999504

In [32]:
from sklearn.metrics import mean_squared_error, r2_score
r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

R2 Score: 0.9994307984053352

In [33]:
y_pred

array([14., 81., 52., ...,  0., 36., 72.])

In [34]:
X_test

,Year,Month,Day,Hour,Minute,Dew Point(F),Humidity(F),Wind Speed(mph),Wind Gust(mph),Pressure(in),...,Condition_T-Storm / Windy,Condition_Thunder,Condition_Thunder / Windy,Condition_Thunder in the Vicinity,Condition_Unknown Precipitation,Condition_Wintry Mix,Condition_Wintry Mix / Windy,Season_Spring,Season_Summer,Season_Winter
198,2010,1,4,13,19,7,73,16,22,29.65,...,0,0,0,0,0,0,0,0,0,1
58934,2014,7,22,17,0,63,54,6,0,29.70,...,0,0,0,0,0,0,0,0,1,0
56509,2014,5,10,22,0,41,67,8,0,29.63,...,0,0,0,0,0,0,0,1,0,0
96200,2017,7,2,11,0,57,77,9,0,29.71,...,0,0,0,0,0,0,0,0,1,0
64836,2015,1,10,18,0,7,68,26,38,30.05,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95580,2017,6,19,17,0,59,61,8,0,29.42,...,0,0,0,0,0,0,0,0,1,0
43501,2013,5,19,12,0,50,82,13,0,29.81,...,0,0,0,0,0,0,0,1,0,0
52880,2014,2,1,10,6,30,93,7,0,29.88,...,0,0,0,0,0,0,0,0,0,1
25330,2012,1,11,0,31,34,93,22,0,29.38,...,0,0,0,0,0,0,0,0,0,1
44960,2013,7,1,12,0,48,43,14,0,29.76,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=RandomForestRegressor(random_state=42), param_grid=param_grid, cv=3, scoring='r2', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Best parameters
print("Best Parameters:", grid_search.best_params_)

# Model training using the best parameters
best_model = grid_search.best_estimator_

# Predictions
y_pred = best_model.predict(X_test)